table DimChannel
	lineageTag: 63230b13-ca29-416c-8ac2-2b1035e926c1

	column channel_id
		dataType: int64
		formatString: 0
		lineageTag: 2c4b3069-ab90-4e5c-877a-c152f1d690d8
		summarizeBy: none
		sourceColumn: channel_id

		annotation SummarizationSetBy = Automatic

	column order_channel
		dataType: string
		lineageTag: 9b4e882d-4425-4c47-a93c-b9d18eec3cd4
		summarizeBy: none
		sourceColumn: order_channel

		annotation SummarizationSetBy = Automatic

	column is_order_ahead
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 289ba5bf-e42a-44d5-80b8-507cf232f17f
		summarizeBy: none
		sourceColumn: is_order_ahead

		annotation SummarizationSetBy = Automatic

	partition DimChannel = m
		mode: import
		source =
				let
				    Origen = vw_orders_starbucks,
				    #"Filas filtradas" = Table.SelectColumns(Origen, {"order_channel", "order_ahead"}),
				    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas"),
				    #"Indice agregado" = Table.AddIndexColumn(#"Duplicados quitados", "channel_id", 1, 1, Int64.Type),
				    #"Columna renombrada" = Table.RenameColumns(#"Indice agregado",{{"order_ahead", "is_order_ahead"}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna renombrada",{{"is_order_ahead", type logical}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

