table DimDate
	lineageTag: 85e3cde8-117a-4e36-8116-3cdf90d1f3e7

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: a7572e08-b40e-4326-a864-b72ea999f7a8
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 881318cc-3143-4355-b43e-ab7dd58b3723
		summarizeBy: none
		sourceColumn: order_date

		variation Variación
			isDefault
			relationship: c17bcb86-ea06-43ca-8f44-9e4ec49e7782
			defaultHierarchy: LocalDateTable_d2151c68-6770-42e3-a2ae-86b6bfde072b.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	column day_of_week
		dataType: string
		lineageTag: bc413359-c616-420f-88a8-43850fcb1459
		summarizeBy: none
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_of_month
		dataType: int64
		formatString: 0
		lineageTag: 26d6367d-ed5c-4087-ad0d-2ee257df3bdf
		summarizeBy: none
		sourceColumn: day_of_month

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: b97856db-85b7-452e-8ee1-bf239fcca3db
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: bcb8738f-f6a8-4a37-82da-c272917a29a6
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: b6faf5cd-1e13-4caf-80b2-93797d628990
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	hierarchy 'Jerarquía Calendario'
		lineageTag: d81318cc-3143-4355-b43e-ab7dd58b3723

		level Año
			column: year
			lineageTag: e81318cc-3143-4355-b43e-ab7dd58b3723

		level Trimestre
			column: quarter
			lineageTag: f81318cc-3143-4355-b43e-ab7dd58b3723

		level Mes
			column: month
			lineageTag: 081318cc-3143-4355-b43e-ab7dd58b3723

		level Día
			column: day_of_month
			lineageTag: 181318cc-3143-4355-b43e-ab7dd58b3723

	partition DimDate = m
		mode: import
		source =
				let
				    Origen = vw_orders_starbucks,
				    #"Filas filtradas" = Table.SelectColumns(Origen, {"order_date", "day_of_week", "day_of_month", "month_num", "quarter_num", "year_num"}),
				    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas"),
				    #"Personalizada agregada" = Table.AddColumn(#"Duplicados quitados", "date_id", each Number.From(Date.ToText([order_date], "yyyyMMdd")), type number),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Personalizada agregada",{{"month_num", "month"}, {"quarter_num", "quarter"}, {"year_num", "year"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

