table DimStore
	lineageTag: 3e8b24ad-5063-4328-97c9-7a88f5d1164a

	column store_id
		dataType: string
		lineageTag: cbbdcaec-5bbf-4fad-8b4c-01122c396ffc
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column store_location_type
		dataType: string
		lineageTag: e4fcc204-bba4-4b4b-aa0c-bdf394cd4da7
		summarizeBy: none
		sourceColumn: store_location_type

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: e451eec3-7c27-4ce5-a809-dca7918c944d
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	hierarchy 'Jerarquía Geográfica'
		lineageTag: f81318cc-3143-4355-b43e-ab7dd58b3723

		level Región
			column: region
			lineageTag: g81318cc-3143-4355-b43e-ab7dd58b3723

		level 'Tipo de Ubicación'
			column: store_location_type
			lineageTag: h81318cc-3143-4355-b43e-ab7dd58b3723

		level Tienda
			column: store_id
			lineageTag: i81318cc-3143-4355-b43e-ab7dd58b3723

	partition DimStore = m
		mode: import
		source =
				let
				    Origen = vw_orders_starbucks,
				    #"Filas filtradas" = Table.SelectColumns(Origen, {"store_id", "store_location_type", "region"}),
				    #"Duplicados quitados" = Table.Distinct(#"Filas filtradas", {"store_id"})
				in
				    #"Duplicados quitados"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

