table DimTime
	lineageTag: ff293971-60e9-4f87-8623-a12c31f48366

	column time
		dataType: dateTime
		formatString: Long Time
		lineageTag: eac7f949-c813-44de-a478-a748182fa0fc
		summarizeBy: none
		sourceColumn: time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column hour_of_day
		dataType: double
		lineageTag: 3366e26a-d31c-4743-ad66-8aea0329ce25
		summarizeBy: none
		sourceColumn: hour_of_day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column time_period
		dataType: string
		lineageTag: 510700d6-e724-4062-ab0d-372c1f721575
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	partition DimTime = m
		mode: import
		source =
				let
				    Origen = vw_orders_starbucks,
				    #"Columnas quitadas" = Table.RemoveColumns(Origen,{"customer_id", "order_id", "order_date", "day_of_week", "order_channel", "store_id", "store_location_type", "region", "customer_age_group", "customer_gender", "is_rewards_member", "cart_size", "num_customizations", "total_spend", "fulfillment_time_min", "drink_category", "has_food_item", "order_ahead", "customer_satisfaction", "order_datetime", "day_of_month", "month_num", "quarter_num", "year_num"}),
				    #"Duplicados quitados" = Table.Distinct(#"Columnas quitadas"),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Duplicados quitados",{{"order_time", "time"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

