table DimTime
	lineageTag: ff293971-60e9-4f87-8623-a12c31f48366

	column time_id
		dataType: int64
		formatString: 0
		lineageTag: 2c4b3069-ab90-4e5c-877a-c152f1d690d8
		summarizeBy: none
		sourceColumn: time_id

		annotation SummarizationSetBy = Automatic

	column order_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: eac7f949-c813-44de-a478-a748182fa0fc
		summarizeBy: none
		sourceColumn: order_time

		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Time

	column hour_of_day
		dataType: int64
		formatString: 0
		lineageTag: 3366e26a-d31c-4743-ad66-8aea0329ce25
		summarizeBy: none
		sourceColumn: hour_of_day

		annotation SummarizationSetBy = Automatic

	column time_period
		dataType: string
		lineageTag: 510700d6-e724-4062-ab0d-372c1f721575
		summarizeBy: none
		sourceColumn: time_period

		annotation SummarizationSetBy = Automatic

	hierarchy 'Jerarquía Temporal'
		lineageTag: b81318cc-3143-4355-b43e-ab7dd58b3723

		level 'Periodo del Día'
			column: time_period
			lineageTag: c81318cc-3143-4355-b43e-ab7dd58b3723

		level 'Hora del Día'
			column: hour_of_day
			lineageTag: d81318cc-3143-4355-b43e-ab7dd58b3723

	partition DimTime = m
		mode: import
		source =
				let
				    Origen = vw_orders_starbucks,
				    #"Columnas seleccionadas" = Table.SelectColumns(Origen, {"hour_of_day", "time_period"}),
				    #"Duplicados quitados" = Table.Distinct(#"Columnas seleccionadas"),
				    #"Personalizada agregada" = Table.AddColumn(#"Duplicados quitados", "time_id", each [hour_of_day], type number),
				    #"Agregada order_time" = Table.AddColumn(#"Personalizada agregada", "order_time", each #time([hour_of_day], 0, 0), type time),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Agregada order_time",{{"time_id", Int64.Type}, {"hour_of_day", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

